version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /hello_input.wdl
    name: changed
    readMePath: badpath.md
    authors:
      - name: David Steinberg
  - subclass: WDL
    primaryDescriptorPath: /wdl-bootcamp/wdl-101-bam.wdl
    name: submodule
    authors:
      - name: David Steinberg
